DROP TABLE IF EXISTS _prisma_migrations;

DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS community;
DROP TABLE IF EXISTS content;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS usr;
DROP TABLE IF EXISTS user_community;
DROP TABLE IF EXISTS vote;