CREATE TABLE IF NOT EXISTS post (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS usr (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);