DROP TABLE IF EXISTS post;

CREATE TABLE IF NOT EXISTS post (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL
);
